version: '3.5'

services:
  db:
    container_name: postgres_container
    image: postgres
    command: [ "postgres", "-c", "log_statement=all" ]
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 999adm
      PGDATA: /data/postgres
      POSTGRES_DB: showroom
    volumes:
      - postgres:/data/
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:8.4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mymail.ru
      PGADMIN_DEFAULT_PASSWORD: adminpassword
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    depends_on:
      - db
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
